name: Build Docs

permissions:
  contents: write

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
          sparse-checkout: 'docs'
          fetch-depth: 0

      - name: Git Config
        run: |
          git config core.fileMode false
        shell: bash

      - name: Build
        run: |
          ls -ld /tmp
          ls -ld .
          docker pull ghcr.io/jurakovic/mkdocs-botr:latest
          chmod +x ./build.sh
          ./build.sh
          git status
        shell: bash
